Repository krkn-chaos/cerberus, pull requests merged in 2021-03, with the labels that each got.

#121 Initialize custom_checks_status
  start_cerberus.py
Labels: ok to test

#124 CI for cerberus
  CI/README.md
  CI/master_test.sh
  CI/run_ci.sh
  CI/run_test.sh
  CI/tests/common.sh
  CI/tests/my_tests
  CI/tests/test-configs/hello_openshift_pod.yaml
  CI/tests/test_daemon_disabled.sh
  CI/tests/test_detailed_data_inspection.sh
  CI/tests/test_list
  CI/tests/test_slack_integration.sh
  docs/installation.md
Labels: ok to test

#125 Initialize custom checks variables
  start_cerberus.py
Labels: P1, ok to test

#126 Add the bot scope permissions
  docs/slack.md
Labels: documentation
